
### Retrieve Data
### NOTE: replace end point with department, course, student, major, teacher
GET http://localhost:3000/course

### Retrieve Course by filter
GET http://localhost:3000/course?course_id=1&course_name=&course_credit=


### -----------------------------------------STUDENT--------------
GET http://localhost:3000/student?student_id=&first_name=Mathew&last_name=

### Posting Data
POST http://localhost:3000/course HTTP/1.1
Content-Type: application/json

{
    "courseName": "testing course2",
    "courseCredit": 4
}

### Posting Student 
POST http://localhost:3000/student HTTP/1.1
Content-Type: application/json

{
    "deptId": 7,
    "firstName": "Testing",
    "lastName": "Tesing",
    "email": "testing@example.com",
    "dateOfBirth": "2001-09-20"
}

### Delete course
DELETE http://localhost:3000/course/13 HTTP/1.1

### Delete student 

DELETE http://localhost:3000/student/26 HTTP/1.1

### Update course
PUT http://localhost:3000/course/4 HTTP/1.1
content-type: application/json

{
    "courseName": "Update Test",
    "courseCredit": 5
}


### --------------------------------------------- course_student-----------------------
GET http://localhost:3000/course_student?course_id=&student_id=


### POST course_student
POST http://localhost:3000/course_student HTTP/1.1
Content-Type: application/json

{
    "course_id": 34,
    "student_id": 24

}

### Delete course_student
DELETE http://localhost:3000/course_student/24 HTTP/1.1

### Update course_student
PUT http://localhost:3000/course_student/64 HTTP/1.1
content-type: application/json

{
    "course_id": 24,
    "student_id": 24
}


###------------------------------MAJOR----------------

POST http://localhost:3000/major HTTP/1.1
Content-Type: application/json

{
    "deptId": 1,
    "majorName": "Add Testing",
    "creditReq": 100
}

### Retrieve Department by filter
GET http://localhost:3000/major?major_id=&major_name=&credit_req=

### Delete major
DELETE http://localhost:3000/major/13 HTTP/1.1

### Update major
PUT http://localhost:3000/major/14 HTTP/1.1
content-type: application/json

{
    "dept_id": 1,
    "major_name": "Update Testing",
    "credit_req": 170
}

###---------------------------------Teacher-------------------
POST http://localhost:3000/teacher HTTP/1.1
Content-Type: application/json

{
    "deptId": 7,
    "firstName": "Add Testing",
    "lastName": "Add Tesing",
    "dateOfBirth": "2001-09-20",
    "phoneNumber": "(472) 899-2192"
}

### Retrieve Teacher by filter
GET http://localhost:3000/teacher?teacher_id=12&first_name=Joel&last_name=

### Update teacher
PUT http://localhost:3000/teacher/12 HTTP/1.1
content-type: application/json

{
    "dept_id": 7,
    "first_name": "Update Testing",
    "last_name": "Update Tesing",
    "date_of_birth": "2001-09-20",
    "phone_number": "(472) 899-2192"
}


### Delete teacher
DELETE http://localhost:3000/teacher/8 HTTP/1.1

###---------------------------------Department-------------------


POST http://localhost:3000/department HTTP/1.1
Content-Type: application/json

{
    "deptName": "Add Testing",
    "location": "Testing Location",
    "campus": "Tesing Campus"

}

### Retrieve Department by filter
GET http://localhost:3000/department?dept_id=&dept_name=&location=&campus=Aria

### Delete Department

DELETE http://localhost:3000/department/12 HTTP/1.1

### Update Department

PUT http://localhost:3000/department/11 HTTP/1.1
content-type: application/json

{
    "dept_name": "Update test",
    "location": "Update Location",
    "campus": "Update campus"
}