
### Retrieve Data
### NOTE: replace end point with department, course, student, major, teacher
GET http://localhost:3000/course

### Posting Data
POST http://localhost:3000/course HTTP/1.1
Content-Type: application/json

{
    "courseName": "testing course2",
    "courseCredit": 4
}

### Posting Student 
POST http://localhost:3000/student HTTP/1.1
Content-Type: application/json

{
    "deptId": 7,
    "firstName": "Testing",
    "lastName": "Tesing",
    "email": "testing@example.com",
    "dateOfBirth": "2001-09-20"
}

### Delete course
DELETE http://localhost:3000/course/13 HTTP/1.1

### Delete student 

DELETE http://localhost:3000/student/26 HTTP/1.1

### Update course
PUT http://localhost:3000/course/4 HTTP/1.1
content-type: application/json

{
    "courseName": "Update Test",
    "courseCredit": 5
}

###------------------------------MAJOR----------------

POST http://localhost:3000/major HTTP/1.1
Content-Type: application/json

{
    "deptId": 1,
    "majorName": "Add Testing",
    "creditReq": 100
}

### Delete major
DELETE http://localhost:3000/major/13 HTTP/1.1

### Update major
PUT http://localhost:3000/major/14 HTTP/1.1
content-type: application/json

{
    "dept_id": 1,
    "major_name": "Update Testing",
    "credit_req": 170
}